FROM python:2.7-alpine

MAINTAINER Enrique Garcia <engapa@gmail.com>

# Required packages
RUN set -x \
    && apk add --update --no-cache --virtual .build-deps \
       bash openssl ca-certificates \
       build-base musl libffi libffi-dev openssl-dev python-dev

RUN set -x \
    && pip install -U setuptools \
    && pip install -U apache-beam

ENTRYPOINT bash
